<?php
define('IMGDIR','themes/default/images/');

$_ENV['imgs'] = array(
  'back'          => IMGDIR.'back.png',
  'debug'         => IMGDIR.'debug.png',
  'deescalate'    => IMGDIR.'deescalate.png',
  'delete'        => IMGDIR.'delete.png',
  'edit'          => IMGDIR.'edit.png',
  'email'         => IMGDIR.'email.png',
  'escalate'      => IMGDIR.'escalate.png',
  'file'          => IMGDIR.'file.png',
  'help'          => IMGDIR.'help.png',
  'hide_closed'   => IMGDIR.'hide_closed.png',
  'high'          => IMGDIR.'high.png',
  'issue_log'     => IMGDIR.'issue_log.png',
  'logo'          => IMGDIR.'logo.png',
  'low'           => IMGDIR.'low.png',
  'motd'          => IMGDIR.'motd.png',
  'move'          => IMGDIR.'move.png',
  'no'            => IMGDIR.'no.png',
  'normal'        => IMGDIR.'normal.png',
  'ok'            => IMGDIR.'ok.png',
  'permission'    => IMGDIR.'permission.png',
  'print'         => IMGDIR.'print.png',
  'private_event' => IMGDIR.'private_event.png',
  'private'       => IMGDIR.'private.png',
  'public'        => IMGDIR.'public.png',
  'search'        => IMGDIR.'search.png',
  'show_closed'   => IMGDIR.'show_closed.png',
  'status'        => IMGDIR.'status.png',
  'style'         => IMGDIR.'style.png',
  'subscribe'     => IMGDIR.'subscribe.png',
  'system'        => IMGDIR.'system.png',
  'unsubscribe'   => IMGDIR.'unsubscribe.png',
  'urgent'        => IMGDIR.'urgent.png',
);

$_ENV['imgs']['menu'] = array(
	'Current Issues'	=> IMGDIR.'issue.png',
	'Groups'			=> IMGDIR.'group.png',
	'Issues'			=> IMGDIR.'issue.png',
	'Logout'			=> IMGDIR.'logout.png',
	'Main' 				=> IMGDIR.'main.png',
	'Menu' 				=> IMGDIR.'menu_base.png',
	'My Assigned'		=> IMGDIR.'issue_myassign.png',
	'My Opened'			=> IMGDIR.'issue_myassign.png',
	'New Group'			=> IMGDIR.'new_group.png',
	'New Issue'			=> IMGDIR.'new_issue.png',
	'New User'			=> IMGDIR.'new_user.png',
	'Preferences'		=> IMGDIR.'preferences.png',
	'Search Issues'		=> IMGDIR.'issue_search.png',
	'Users'				=> IMGDIR.'user.png'
);
?>
