<?php
define('IMGDIR','themes/default/images/png/');

$_ENV['imgs'] = array(
  'announce'      => IMGDIR.'announce.png',
  'back'          => IMGDIR.'back.png',
  'category'      => IMGDIR.'category.png',
  'debug'         => IMGDIR.'debug.png',
  'deescalate'    => IMGDIR.'deescalate.png',
  'delete'        => IMGDIR.'delete.png',
  'edit'          => IMGDIR.'edit.png',
  'email'         => IMGDIR.'email.png',
  'escalate'      => IMGDIR.'escalate.png',
  'file'          => IMGDIR.'file.png',
  'group'         => IMGDIR.'group.png',
  'help'          => IMGDIR.'help.png',
  'hide_closed'   => IMGDIR.'hide_closed.png',
  'high'          => IMGDIR.'high.png',
  'issue_log'     => IMGDIR.'issue_log.png',
  'logo'          => IMGDIR.'logo.png',
  'low'           => IMGDIR.'low.png',
  'motd'          => IMGDIR.'motd.png',
  'move'          => IMGDIR.'move.png',
  'new_announce'  => IMGDIR.'new_announce.png',
  'new_group'     => IMGDIR.'new_group.png',
  'new_issue'     => IMGDIR.'new_issue.png',
  'new_user'      => IMGDIR.'new_user.png',
  'no'            => IMGDIR.'no.png',
  'normal'        => IMGDIR.'normal.png',
  'ok'            => IMGDIR.'ok.png',
  'permission'    => IMGDIR.'permission.png',
  'print'         => IMGDIR.'print.png',
  'private_event' => IMGDIR.'private_event.png',
  'private'       => IMGDIR.'private.png',
  'product'       => IMGDIR.'product.png',
  'public'        => IMGDIR.'public.png',
  'search'        => IMGDIR.'search.png',
  'show_closed'   => IMGDIR.'show_closed.png',
  'status'        => IMGDIR.'status.png',
  'style'         => IMGDIR.'style.png',
  'subscribe'     => IMGDIR.'subscribe.png',
  'system'        => IMGDIR.'system.png',
  'unsubscribe'   => IMGDIR.'unsubscribe.png',
  'urgent'        => IMGDIR.'urgent.png',
  'user'          => IMGDIR.'user.png'
);
?>
